#!/usr/bin/env ruby

require 'parallel'

CMD = %w(destroy provision up)

if ARGV.empty? || !CMD.include?(ARGV.first)
  puts 'Usage: ./manager <command>'
  puts ''
  puts 'Commands:'
  puts '    destroy    stops and deletes all traces of the vagrant machine'
  puts '    provision  provisions the vagrant machine'
  puts '    up         starts and provisions the vagrant environment'
  exit 1
end

command = ARGV.first
command += ' --provider libvirt' if command == 'up'
command += ' -f'                 if command == 'destroy'

number = Dir::glob('instance-*').size

Parallel.each 1..number, in_threads: number do |i|
  sleep i
  puts "==> #{command} instance-#{i}..."
  result = system "cd instance-#{i} && vagrant #{command} > /dev/null"
  puts "\e[32m==> Success #{command} instance-#{i}\e[0m" if result
  puts "\e[31m==> Failure #{command} instance-#{i}\e[0m" unless result
end
